### ISSUE TITLE
"An internal error ocurred while attempting to perform this command"

### ISSUE THREAD

**Issue by Pxdrinnkkj** [LandlordPlugin/LandLord#180]
I'm using the last release of LandLord plugin (4.363) in an Aternos server with PaperMC, in 1.20.4, and when I use the "/land shop" or "/land manage" commands, the message present on the title appears in the chat, i'm using the last version of Vault, WorldGuard and WorldEdit, as a economy provider, i'm using EssentialsX, i tried using other economy provider and permission plugins, but that doesn't seems to be the problem, in the config file, i changed from chat confirmations to GUI, and the other GUIs work perfectly.

**Comment by rainbowdashlabs** [comment]
Thats an internal issue we are aware of and is caused by a change in the player head creation internally. We are working on a fix
