### ISSUE TITLE
Bump java version to java 11

### ISSUE THREAD

**Issue by RainbowDashLabs** [LandlordPlugin/LandLord#24]
With progression caused by minecraft version 1.17, the community finally start updating their legacy java versions.

As of today (15.06.2021) around 35% of the Landlord users still use java 8. We suspect this number to decrease even more in the near future.

Due to md5 bytecode check fuckup 1.13.2 only runs with java 12, although it would run perfectly fine with java 16.

Thats why we decided to switch to java 11 to get at least some of the advantages of the last years.

We should combine the bumping of the version with changing code according to new methods which were introduced till java 11

**Comment by Aurelien30000** [comment]
EldoUtils 1.12.0 supporting Java 11+ fits perfectly ;) Will be addressed as soon as possible.
