### ISSUE TITLE
ILandlord castclass exception

### ISSUE THREAD

**Issue by mmuziek** [LandlordPlugin/LandLord#37]
Well i must say i tried both with the core import and with just the api.
In both cases when loading the api:

`this.api = (ILandLord) pl.getServer().getPluginManager().getPlugin("Landlord");`
CastClass exception is trown. it cannot cast the class to ILandLord.
which in my opinion is a bit strange however when looking into your code you inherit the class in your main class.
which can cause this issue. in the end it might be the best to use the mainclass as a redirect and add a public ILandLord getAPI() to the mainclass so people can get the api.

currently im working on adding support for landlord to bluemap the code is ready just this class load is failing since it does load in my coding software but in the release its not there or at least not working as it should

**Comment by SirYwell** [comment]
Could you show at least the full stacktrace + server software/version?

**Comment by mmuziek** [comment]
https://prnt.sc/1sofb8x does this help the full stacktrace returns into the same as this
com.mmuziek.BME.Modules.MCGLandLord.tryregister(MCGLandLord.java:42) << thats the line where it registers
 com.mmuziek.BME.BMECore.loadmodules(BMECore.java:564)
 com.mmuziek.BME.BMECore.lambda$onEnable$0(BMECore.java:97)
 de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:200)
 de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:149)
 de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:269)
 de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:140)
 org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
 org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
 java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
 java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
 java.base/java.lang.Thread.run(Thread.java:831)
 
 Testing on spigot 1.17.1

**Comment by RainbowDashLabs** [comment]
Please send the full stack trace you are missing the most important part.

**Comment by mmuziek** [comment]
This is the stacktrace nothing more to it

What are u missing?

**Comment by SirYwell** [comment]
The more information the better, full logs would be benefitial. My first guess would be that you're currently shading LandLord into your plugin

**Comment by RainbowDashLabs** [comment]
> The more information the better, full logs would be benefitial. My first guess would be that you're currently shading LandLord into your plugin

Thats my guess too, but I am missing the end of the error message, which would indicate this.

**Comment by mmuziek** [comment]
Its stated maven provided not maven shade i will try to pull the last log up

**Comment by mmuziek** [comment]
the full log is useless since its my own Error catching handling this but i printed the raw exception for you :
https://pastebin.com/QHyuSKMM

**Comment by SirYwell** [comment]
> biz.princeps.landlord.LandLord is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @2f016c72

> biz.princeps.landlord.api.ILandLord is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @373e59eb

The classes are loaded by different class loaders, as expected.
This is either caused by shading LandLord or by reloading the server/single plugins.

**Comment by mmuziek** [comment]
both are no. but i completely cleaned my project and removed all refferences and reimported this after wiping the maven cache and it seems to work now
