### ISSUE TITLE
Permanent Claimed Chunk Particles

### ISSUE THREAD

**Issue by CoderBoyo** [LandlordPlugin/LandLord#6]
Would it be possible to implement permanent particles, for example if a player claims a chunk that chunk would be highlighted for other players to see from a distance. If the team is currently busy with other projects, I will begin to work on this on a fork and if everything goes well I'll submit a pull request.

**Comment by RainbowDashLabs** [comment]
Feel free to start a implementation of this. We are happy for any contribution to this project ^^

This feature could be fairly large, especially because it needs to be efficient as well.

If you implement it you could open a WIP PR if you need any feedback from our side ^^

**Comment by CoderBoyo** [comment]
Sorry can you help me with something? Were is the place were the claim command is run and were you check with the world guard stuff to see the claimed chunks?

**Comment by Aurelien30000** [comment]
> Sorry can you help me with something? Were is the place were the claim command is run and were you check with the world guard stuff to see the claimed chunks?

https://github.com/LandlordPlugin/LandLord/blob/development/LandLord-core/src/main/java/biz/princeps/landlord/commands/claiming/Claim.java#L63 If the land is free, this method just returns ``null``.

**Comment by CoderBoyo** [comment]
I have actually done this but not in the actual plugin. I have done this is  my own. Note please don't use this code as a spent a lot of time working it out. Code:
`@EventHandler
    public void claim(LandPostClaimEvent e) {
        data d = new data(main);
        if((ArrayList<Location>) d.getConfig().get("Claims")!=null) {
            ArrayList<Location> loc = (ArrayList<Location>) d.getConfig().get("Claims");
            loc.add(e.getLand().getALocation());
            d.getConfig().set("Claims", loc);
            d.saveConfig();
        } else {
            ArrayList<Location> loc = new ArrayList<>();
            loc.add(e.getLand().getALocation());
            d.getConfig().set("Claims", loc);
            d.saveConfig();
        }
    }`
`@EventHandler
    public void unclaim(LandUnclaimEvent e) {
        data d = new data(main);
        ArrayList<Location> loc = (ArrayList<Location>) d.getConfig().get("Claims");
        loc.remove(getint(e.getLand().getALocation(),loc));
        d.getConfig().set("Claims",loc);
        d.saveConfig();
    }`
`public int getint(Location location,ArrayList<Location> loc) {
        int get = 0;
        for(int i = 0; i<loc.size();i++) {
            if(loc.get(i)==location) {
               get = i;
            }
        }
        return get;
    }`
`@Override
    public void run() {
        data d = new data(main);
        if((ArrayList<Location>) d.getConfig().get("Claims") != null) {
            ArrayList<Location> chunks = (ArrayList<Location>) d.getConfig().get("Claims");
            for (int i = 0; i < chunks.size(); i++) {
                Chunk chunk = chunks.get(i).getWorld().getChunkAt(chunks.get(i));
                int minX = chunk.getX() << 4;
                int minZ = chunk.getZ() << 4;
                int minY = 0;
                World world = chunk.getWorld();
                for (int y = minY; y < 121; y++) {
                    for (int x = minX; x < minX + 16; x++) {
                        Location loc1 = new Location(chunk.getWorld(), x, y, minZ);
                        Object packet = particles.HAPPY_VILLAGER().packet(true, loc1);
                        serverConn.sendPacket(loc1, 30D, packet);
                        Location loc2 = new Location(chunk.getWorld(), x, y, minZ + 16);
                        Object packet2 = particles.HAPPY_VILLAGER().packet(true, loc2);
                        serverConn.sendPacket(loc2, 30D, packet2);

                    }
                    for (int z = minZ; z < minZ + 16; z++) {
                        Location loc3 = new Location(chunk.getWorld(), minX, y, z);
                        Object packet = particles.HAPPY_VILLAGER().packet(true, loc3);
                        serverConn.sendPacket(loc3, 30D, packet);
                        Location loc4 = new Location(chunk.getWorld(), minX + 16, y, z);
                        Object packet2 = particles.HAPPY_VILLAGER().packet(true, loc4);
                        serverConn.sendPacket(loc4, 30D, packet2);
                    }

                }
            }
        }
    }`
Uses particleapi:
https://www.spigotmc.org/resources/particlenativeapi-1-7.76480/#:~:text=ParticleNativeAPI%20is%20a%20particle%20spawning%20API%20for%20Spigot,compatible%20down%20to%20MC%201.7%20%28includes%20removed%20particles%21%29%2C
Again please don't use this code :) ty

**Comment by Aurelien30000** [comment]
Seems a good starting point, don't hesitate to put your code on gist.github.com ;)

**Comment by CoderBoyo** [comment]
It's been quite a long time since I said this and I just realized I never published the plugin I made.. Oops..

**Comment by RainbowDashLabs** [comment]
Just one small hint from my side.
You don't need an external api for sending particle packets to players.
You can simply use player#spawnParticle
